default_platform(:ios)

platform :ios do
  desc "Pass all test for main target"
  lane :pass_tests do
  	test_scheme(scheme: "RxMagicPills-macOS", configuration: "Debug", name: "mac")
  	sh "curl -s https://codecov.io/bash | bash -s -- -F mac -J 'RxMagicPills'"

  	test_scheme(scheme: "RxMagicPills-tvOS", configuration: "Debug", name: "tv")
  	sh "curl -s https://codecov.io/bash | bash -s -- -F tv -J 'RxMagicPills'"

  	test_scheme(scheme: "RxMagicPills-iOS", configuration: "Debug", name: "iOS")
  	sh "curl -s https://codecov.io/bash | bash -s -- -F ios -J 'RxMagicPills'"
  end
end
